---
packageName: vault-auto-init
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "vault-init", "label": "vault-init_linux_amd64" }
        ]
      }
  ]
  - "@semantic-release/release-notes-generator"
  - [
      "semantic-release-slack-bot",
      {
        "notifyOnSuccess": true,
        "notifyOnFail": true
      }
  ]
