version: 2.1
orbs:
  semantic-release: proxyco/semantic-release@3.0.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: CGO_ENABLE=0 GOOS=linux go build -o vault-init -v .
workflows:
  build:
    jobs:
      - build
  tag:
    jobs:
      - semantic-release/release:
          context: global-vars
          filters:
            branches:
              only: /main/
          config_file: .circleci/.releaserc.yml