version: 2.1
orbs:
  semantic-release: proxyco/semantic-release@3.0.0
jobs:
  build:
    working_directory: $GOROOT/app
    docker:
      - image: circleci/golang:1.15.3
    steps:
      - checkout
      - run:
          name: Build binary
          command: CGO_ENABLE=0 GOOS=linux go build -o vault-init -v .
workflows:
  build:
    jobs:
      - build
  tag:
    jobs:
      - semantic-release/release:
          context: global-vars
          filters:
            branches:
              only: /main/
          config_file: .circleci/.releaserc.yml